{
 "title": "url-shortener-demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_in_flight", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status: 4xx|5xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by(path, status) (rate(http_requests_total{status=~\"4..|5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[1m])) / sum(rate(http_requests_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}