name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  apply-prod:
    name: Apply Prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: prod
    env:
      TF_VAR_environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_PROD_ROLE_APPLY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Mask AWS Account ID
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "::add-mask::$ACCOUNT_ID"

      - name: Terraform Init
        working-directory: infra
        env:
          TF_CLI_ARGS_init: >-
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"
            -backend-config="key=${{ secrets.TF_STATE_KEY_PROD }}"
            -backend-config="region=${{ secrets.AWS_REGION }}"
            -backend-config="kms_key_id=${{ secrets.TF_STATE_KMS_KEY }}"
            -backend-config="use_lockfile=true"
        run: terraform init > /dev/null

      - name: Terraform Plan
        working-directory: infra
        env:
          TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
          TF_VAR_project_name: ${{ vars.TF_VAR_PROJECT_NAME }}
          TF_VAR_aws_region: ${{ vars.TF_VAR_AWS_REGION }}
        id: plan
        run: terraform plan -input=false -out=prod.tfplan 2>&1 | tee prod_plan.log > /dev/null

      - name: Upload Plan Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plan-log
          path: infra/prod_plan.log

      - name: Terraform Apply
        working-directory: infra
        env:
          TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
          TF_VAR_project_name: ${{ vars.TF_VAR_PROJECT_NAME }}
          TF_VAR_aws_region: ${{ vars.TF_VAR_AWS_REGION }}
        run: terraform apply -auto-approve prod.tfplan 2>&1 | tee prod_apply.log > /dev/null

      - name: Upload Apply Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfapply-log
          path: infra/prod_apply.log

      - name: Cleanup sensitive files
        if: always()
        working-directory: infra
        run: rm -f prod.tfplan prod_apply.log prod_plan.log
